apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml

- ./httpr/httpr-namespace.yaml
- ./httpr/httpr-service.yaml
- ./httpr/httpr-deployment.yaml