apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (c4137012e)
  labels:
    io.kompose.service: fluentbit
  name: fluentbit
  namespace: httpr
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: fluentbit
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (c4137012e)
      labels:
        io.kompose.network/otel-default: "true"
        io.kompose.service: fluentbit
    spec:
      containers:
        - image: fluent/fluent-bit:latest
          name: fluentbit
          ports:
            - containerPort: 3001
          resources: {}
          volumeMounts:
            - name: docker-metadata
              mountPath: /fluent-bit/bin/docker-metadata              
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/            
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: mnt
              mountPath: /mnt
              readOnly: true            
      restartPolicy: Always
      volumes:
        - name: docker-metadata
          configMap:
            name: docker-metadata
        - name: fluent-bit-config
          configMap:
            name: fluent-bit-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: mnt
          hostPath:
            path: /mnt
status: {}
