---
apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-ui
  namespace: httpr
data:
  jaeger-ui.json: |
   {
     "monitor": {
       "menuEnabled": true
     },
     "dependencies": {
       "menuEnabled": true
     }
   }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sampling-strategies
  namespace: httpr
data:
  sampling_strategies.json: |
   {
     "default_strategy": {
       "type": "probabilistic",
       "param": 1
      }
   }