apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-ui
  namespace: httpr
data:
  jaeger-ui.json: |
    {
    "monitor": {
      "menuEnabled": true
    },
    "dependencies": {
      "menuEnabled": true
    }
    }
