apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: httpr
data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s 
      evaluation_interval: 15s

    scrape_configs:
      - job_name: otel_collector
        scrape_interval: 5s
        static_configs:
          - targets: ['collector:8889']

      - job_name: 'prometheus'
        static_configs:
          - targets: [ '0.0.0.0:9090' ]